#!/usr/bin/env bun
// Scans server/public/ and writes server/src/generated/embedded-public.ts so
// that `bun build --compile` embeds every static asset into the tmpod binary.
// Each asset is imported with `with { type: "file" }`, and a manifest maps
// URL paths to the embedded file paths that Bun.file() can read at runtime.

import { readdirSync, statSync, mkdirSync, writeFileSync, existsSync } from "fs";
import path from "path";

const SCRIPT_DIR = import.meta.dir;
const SERVER_DIR = path.resolve(SCRIPT_DIR, "..");
const PUBLIC_DIR = path.join(SERVER_DIR, "public");
const GENERATED_DIR = path.join(SERVER_DIR, "src", "generated");
const OUTPUT_FILE = path.join(GENERATED_DIR, "embedded-public.ts");

function listFiles(dir: string, base: string = dir): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    const s = statSync(full);
    if (s.isDirectory()) {
      out.push(...listFiles(full, base));
    } else if (s.isFile()) {
      out.push(path.relative(base, full));
    }
  }
  return out;
}

mkdirSync(GENERATED_DIR, { recursive: true });

const files = existsSync(PUBLIC_DIR) ? listFiles(PUBLIC_DIR).sort() : [];

const lines: string[] = [
  "// AUTO-GENERATED by scripts/generate-embedded-public.ts — do not edit.",
  "// Embeds server/public/ into the compiled tmpod binary.",
  "",
];

files.forEach((rel, i) => {
  const importPath = "../../public/" + rel.split(path.sep).join("/");
  lines.push(`import file${i} from "${importPath}" with { type: "file" };`);
});

if (files.length > 0) lines.push("");

lines.push("export const embeddedFiles: Record<string, string> = {");
files.forEach((rel, i) => {
  const urlPath = "/" + rel.split(path.sep).join("/");
  lines.push(`  ${JSON.stringify(urlPath)}: file${i},`);
});
lines.push("};");
lines.push("");

writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");

console.log(`Generated ${path.relative(SERVER_DIR, OUTPUT_FILE)} with ${files.length} embedded file(s)`);
